version: '3'

services:
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: .
      args:
        NODE_ENV: development
    ports:
      - 2010:2010
      - 9229:9229
    volumes:
      - ./server:/opt/ccashcow/server:delegated
      - ./server/package.json:/opt/ccashcow/server/package.json
      - ./server/package-lock.json:/opt/ccashcow/server/package-lock.json
      - unused1:/opt/ccashcow/server/node_modules
      - database:/opt/ccashcow/database
    command: npm run watch-start
    env_file: ./server/.env
  web:
    build:
      dockerfile: ./web/Dockerfile
      context: .
      args:
        NODE_ENV: development
    ports:
      - 2011:2011
    volumes:
      - ./web:/opt/ccashcow/web:delegated
      - ./web/package.json:/opt/ccashcow/web/package.json
      - ./web/package-lock.json:/opt/ccashcow/web/package-lock.json
      - unused2:/opt/ccashcow/web/node_modules
    command: npm run start
    env_file: ./web/.env

volumes:
  unused1:
  unused2:
  database: